---
# This file is managed by the stacks toolchain. It may be overwritten by
# updates to the template. Your customizations should be placed inside the
# .kitchen.local.yml, which will not be overwritten by newer templates.
# If you need to override the driver, do it in ~/.kitchen/config.yml or using
# environment variables like VAGRANT_DEFAULT_PROVIDER.

driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: true}]  # elastic
  - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]  # kibana
  - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}] # ssl

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1
  client_rb:
    environment: _default
  attributes:
    firewall:
      ubuntu_iptables: true
      allow_ssh: true
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    elasticsearch:
      network:
        host: '127.0.0.1'
      index:
        number_of_replicas: 0
        # so the kitchen node doesn't have unallocated replica shards
        # and comes up green (healthy) instead of yellow
      discovery:
        zen:
          minimum_master_nodes: 1 # since search returns more than one, but they are fake
    elkstack:
      config:
        iptables:
          enabled: true
        kibana:
          password: 'kibana'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.8
    run_list:
    - recipe[yum]
    attributes:
      java:
        jdk_version: 8
  - name: centos-7
    run_list:
    - recipe[yum]
    attributes:
      java:
        jdk_version: 8

suites:
  - name: default # server
    data_bags_path: "test/integration/forwarder/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/forwarder/encrypted_data_bag_secret"
    run_list:
      - recipe[java::default]
      - recipe[elkstack::default]

  - name: default-centos-syslog-ng
    run_list:
      - recipe[yum-epel::default]
      - recipe[java::default]
      - recipe[elkstack::default]
    excludes: # upstream syslog-ng only supports CentOS
      - ubuntu-12.04
      - ubuntu-14.04
      - centos-7
    attributes:
      elkstack:
        config:
          syslog_pkg: 'syslog-ng'
      kibana:
        version: '4.0.2-linux-x64'
        file:
          url: 'https://download.elastic.co/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz'
      java:
        jdk_version: '7'

  - name: lumberjack # server with lumberjack disabled
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[elkstack::java]
      - recipe[elkstack::cluster] # not testing single, it's practically the same
    attributes:
      elkstack:
        config:
          lumberjack_data_bag: false
      elasticsearch:
        discovery:
          zen:
            minimum_master_nodes: 1 # since search returns more than one, but they are fake

  - name: agent # java agent with server
    run_list:
      - recipe[wrapper::logstash_override]
      - recipe[java::default]
      - recipe[elkstack::agent]

  - name: forwarder # alternative golang agent with server
    data_bags_path: "test/integration/forwarder/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/forwarder/encrypted_data_bag_secret"
    run_list:
      - recipe[elkstack::forwarder]

  - name: wrapper
    data_bags_path: "test/integration/forwarder/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/forwarder/encrypted_data_bag_secret"
    run_list:
      - recipe[wrapper::elk]

<% if ENV['RACKSPACE_MONITORING_USERNAME'] && ENV['RACKSPACE_MONITORING_API_KEY'] %>
<%# Disabling backup as elasticsearch_backup seems to fail if you don't give the good credentials %>
  - name: monitoring # server
    run_list:
      - recipe[java::default]
      - recipe[elkstack::default]
    attributes:
      elkstack:
        config:
          backups:
            enabled: false
          cloud_monitoring:
            enabled: true
      rackspace:
        cloud_credentials:
          username: <%= ENV['RACKSPACE_MONITORING_USERNAME'] %>
          api_key: <%= ENV['RACKSPACE_MONITORING_API_KEY'] %>
<% end %>
